### PR TITLE
Updating URL Schema - "turtles.docs.rancher.com"

### PR DESCRIPTION
**Pull request by sunilarjun**
Adding the updated URL schema for Rancher Turtles documentation in the config and the CNAME file. Additionally updated links that were throwing errors while attempting `yarn start`.

### CODE REVIEW

**Comment by Danil-Grigorev** [comment]
I think this is superseded by https://github.com/rancher/turtles-docs/pull/74

**Comment by salasberryfin** [comment]
I think this also configures the docs to be hosted on a `*rancher.com` domain so I don't know if it's completely superseded by #74.

**Comment by Danil-Grigorev** [comment]
@sunilarjun Can you please provide reasoning for CNAME change? We are hosting this currently under https://docs.rancher-turtles.com/. Who owns the CNAME?

**Comment by sunilarjun** [comment]
Hello @Danil-Grigorev! The CNAME change was approved in the site standardization meeting to align with SUSE docs sites, and other changes are listed in the [main issue](https://github.com/rancher/turtles-docs/issues/64) as well. The CNAME is currently maintained by EIO and there is a ticket to update the subdomain here: https://github.com/rancherlabs/eio/issues/2141. I believe the ticket must be completed first, and then this PR can take effect.

**Comment by furkatgofurov7** [comment]
CNAME PR https://github.com/SUSE/suse-it-infra/pull/4140 is merged, this should be ready

**Review by furkatgofurov7 — APPROVED** [review]

**Review by salasberryfin — APPROVED** [review]

**Review by mbologna — APPROVED** [review]

**Pull request merged**
